<script>

window.charla_property_id = "<?php echo $block->escapeJs($block->getPropertyId()) ?>";

window.addEventListener('load', () => {

    if (!window.charla_property_id) return;

    const widgetElement = document.createElement('charla-widget');
    widgetElement.setAttribute("p", window.charla_property_id);
    widgetElement.setAttribute("shop-data", '<?php echo $block->escapeJs($block->getCartTotals()) ?>');
    document.body.appendChild(widgetElement) ;

    const widgetCode = document.createElement('script');
    widgetCode.src = 'https://app.charla.com/widget/widget.js';
    document.body.appendChild(widgetCode);

});

</script>
